// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd-jK5zrNUuyRSz4rOlAyqhxhBoI0olUA',
    appId: '1:1091646722793:web:f725a8ae04f1dc6d845678',
    messagingSenderId: '1091646722793',
    projectId: 'balanced-59cd2',
    authDomain: 'balanced-59cd2.firebaseapp.com',
    storageBucket: 'balanced-59cd2.firebasestorage.app',
    measurementId: 'G-1RJNSB71HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6XkXNn9rXM611RiU8WNrOBl5Allrrles',
    appId: '1:1091646722793:android:b8ec48478997ac4e845678',
    messagingSenderId: '1091646722793',
    projectId: 'balanced-59cd2',
    storageBucket: 'balanced-59cd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1rP9V1aDJlb7szL_g8FGvC0LBuc2O7x4',
    appId: '1:1091646722793:ios:682219aa0bea78dd845678',
    messagingSenderId: '1091646722793',
    projectId: 'balanced-59cd2',
    storageBucket: 'balanced-59cd2.firebasestorage.app',
    iosBundleId: 'com.example.balancedMeall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1rP9V1aDJlb7szL_g8FGvC0LBuc2O7x4',
    appId: '1:1091646722793:ios:682219aa0bea78dd845678',
    messagingSenderId: '1091646722793',
    projectId: 'balanced-59cd2',
    storageBucket: 'balanced-59cd2.firebasestorage.app',
    iosBundleId: 'com.example.balancedMeall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd-jK5zrNUuyRSz4rOlAyqhxhBoI0olUA',
    appId: '1:1091646722793:web:0251f7a265b4e1ee845678',
    messagingSenderId: '1091646722793',
    projectId: 'balanced-59cd2',
    authDomain: 'balanced-59cd2.firebaseapp.com',
    storageBucket: 'balanced-59cd2.firebasestorage.app',
    measurementId: 'G-RLP58LV4ZW',
  );

}